sap.ui.define([], function () {
    "use strict";

    return {
        expectedColumnCount: [64],
        sheetRange: {
            startRow: 6,
            startCol: 0
        },
        headerRowIndex: 8,
        dataStartOffset: 9,
        buildPayload: function (row) {
            return {
                RuleFieldID: row[0]?.toString() || "",
                Ha001: row[1]?.toString() || "",
                Pi001: row[2]?.toString() || "",
                Pi075: row[3]?.toString() || "",
                Pi076: row[4]?.toString() || "",
                Pi077: row[5]?.toString() || "",
                Pi078: row[6]?.toString() || "",
                Pi079: row[7]?.toString() || "",
                XyY71: row[8]?.toString() || "",
                Pi080: row[9]?.toString() || "",
                XyY72: row[10]?.toString() || "",
                XyY73: row[11]?.toString() || "",
                XyY74: row[12]?.toString() || "",
                XyY75: row[13]?.toString() || "",
                XyY76: row[14]?.toString() || "",
                XyY77: row[15]?.toString() || "",
                XyY78: row[16]?.toString() || "",
                XyY79: row[17]?.toString() || "",
                XyY80: row[18]?.toString() || "",
                XyY81: row[19]?.toString() || "",
                Ad001: row[20]?.toString() || "",
                Ad083: row[21]?.toString() || "",
                Ad084: row[22]?.toString() || "",
                Ad085: row[23]?.toString() || "",
                Ad086: row[24]?.toString() || "",
                Ad087: row[25]?.toString() || "",
                Ad088: row[26]?.toString() || "",
                Ad089: row[27]?.toString() || "",
                Ad090: row[28]?.toString() || "",
                Ad091: row[29]?.toString() || "",
                Ad092: row[30]?.toString() || "",
                Ad002: row[31]?.toString() || "",
                Ad093: row[32]?.toString() || "",
                Ad094: row[33]?.toString() || "",
                Ad095: row[34]?.toString() || "",
                Ad096: row[35]?.toString() || "",
                Ad097: row[36]?.toString() || "",
                Ad098: row[37]?.toString() || "",
                Ad099: row[38]?.toString() || "",
                Ad100: row[39]?.toString() || "",
                Ad101: row[40]?.toString() || "",
                Ad102: row[41]?.toString() || "",
                XyY82: row[42]?.toString() || "",
                Ji061: row[43]?.toString() || "",
                Ji062: row[44]?.toString() || "",
                Ji063: row[45]?.toString() || "",
                Ji064: row[46]?.toString() || "",
                Ji065: row[47]?.toString() || "",
                Ji066: row[48]?.toString() || "",
                Ji067: row[49]?.toString() || "",
                Ji068: row[50]?.toString() || "",
                Py077: row[51]?.toString() || "",
                Py078: row[52]?.toString() || "",
                Py079: row[53]?.toString() || "",
                Py080: row[54]?.toString() || "",
                Py081: row[55]?.toString() || "",
                Py082: row[56]?.toString() || "",
                Py083: row[57]?.toString() || "",
                Py084: row[58]?.toString() || "",
                Py085: row[59]?.toString() || "",
                Py086: row[60]?.toString() || "",
                Py087: row[61]?.toString() || "",
                Py088: row[62]?.toString() || "",
                Py089: row[63]?.toString() || "",

            };
        }
    };
});
