sap.ui.define([], function () {
    "use strict";

    return {
        entitySet: "/zemp_header_argSet",
        navigationProperty: "TO_ITEMS_ARG",
        itemEntitySet: "/zemp_item_argSet",

        expectedColumnCount: [64],
        sheetRange: {
            startRow: 6,
            startCol: 0
        },
        headerRowIndex: 8,
        dataStartOffset: 9,
        buildPayload: function (row) {
            return {
                RuleFieldID: row[0]?.toString() || "",
                HA001: row[1]?.toString() || "",
                PI001: row[2]?.toString() || "",
                PI075: row[3]?.toString() || "",
                PI076: row[4]?.toString() || "",
                PI077: row[5]?.toString() || "",
                PI078: row[6]?.toString() || "",
                PI079: row[7]?.toString() || "",
                XY71: row[8]?.toString() || "",
                PI080: row[9]?.toString() || "",
                XY72: row[10]?.toString() || "",
                XY73: row[11]?.toString() || "",
                XY74: row[12]?.toString() || "",
                XY75: row[13]?.toString() || "",
                XY76: row[14]?.toString() || "",
                XY77: row[15]?.toString() || "",
                XY78: row[16]?.toString() || "",
                XY79: row[17]?.toString() || "",
                XY80: row[18]?.toString() || "",
                XY81: row[19]?.toString() || "",
                AD001: row[20]?.toString() || "",
                AD083: row[21]?.toString() || "",
                AD084: row[22]?.toString() || "",
                AD085: row[23]?.toString() || "",
                AD086: row[24]?.toString() || "",
                AD087: row[25]?.toString() || "",
                AD088: row[26]?.toString() || "",
                AD089: row[27]?.toString() || "",
                AD090: row[28]?.toString() || "",
                AD091: row[29]?.toString() || "",
                AD092: row[30]?.toString() || "",
                AD002: row[31]?.toString() || "",
                AD093: row[32]?.toString() || "",
                AD094: row[33]?.toString() || "",
                AD095: row[34]?.toString() || "",
                AD096: row[35]?.toString() || "",
                AD097: row[36]?.toString() || "",
                AD098: row[37]?.toString() || "",
                AD099: row[38]?.toString() || "",
                AD100: row[39]?.toString() || "",
                AD101: row[40]?.toString() || "",
                AD102: row[41]?.toString() || "",
                XY82: row[42]?.toString() || "",
                JI061: row[43]?.toString() || "",
                JI062: row[44]?.toString() || "",
                JI063: row[45]?.toString() || "",
                JI064: row[46]?.toString() || "",
                JI065: row[47]?.toString() || "",
                JI066: row[48]?.toString() || "",
                JI067: row[49]?.toString() || "",
                JI068: row[50]?.toString() || "",
                PY077: row[51]?.toString() || "",
                PY078: row[52]?.toString() || "",
                PY079: row[53]?.toString() || "",
                PY080: row[54]?.toString() || "",
                PY081: row[55]?.toString() || "",
                PY082: row[56]?.toString() || "",
                PY083: row[57]?.toString() || "",
                PY084: row[58]?.toString() || "",
                PY085: row[59]?.toString() || "",
                PY086: row[60]?.toString() || "",
                PY087: row[61]?.toString() || "",
                PY088: row[62]?.toString() || "",
                PY089: row[63]?.toString() || ""

            };
        }
    };
});
