sap.ui.define([], function () {
    "use strict";

    return {
        expectedColumnCount: [80, 44],
        sheetRange: {
            startRow: 6,
            startCol: 0
        },
        headerRowIndex: 8,
        dataStartOffset: 9,
        buildPayload: function (row) {
            return {
                RuleFieldID: row[0]?.toString() || "",
                Ha001: row[1]?.toString() || "",
                Pi001: row[2]?.toString() || "",
                Pi002: row[3]?.toString() || "",
                Pi003: row[4]?.toString() || "",
                Pi004: row[5]?.toString() || "",
                Pi005: row[6]?.toString() || "",
                Pi006: row[7]?.toString() || "",
                Pi007: row[8]?.toString() || "",
                Pi008: row[9]?.toString() || "",
                Pi009: row[10]?.toString() || "",
                Pi010: row[11]?.toString() || "",
                Pi011: row[12]?.toString() || "",
                Pi012: row[13]?.toString() || "",
                XY009: row[14]?.toString() || "",
                XY010: row[15]?.toString() || "",
                XY011: row[16]?.toString() || "",
                XY012: row[17]?.toString() || "",
                XY013: row[18]?.toString() || "",
                XY014: row[19]?.toString() || "",
                XY015: row[20]?.toString() || "",
                XY016: row[21]?.toString() || "",
                Ad001: row[22]?.toString() || "",
                Ad003: row[23]?.toString() || "",
                Ad004: row[24]?.toString() || "",
                Ad005: row[25]?.toString() || "",
                Ad006: row[26]?.toString() || "",
                Ad007: row[27]?.toString() || "",
                Ad008: row[28]?.toString() || "",
                Ad009: row[29]?.toString() || "",
                Ad002: row[30]?.toString() || "",
                Ad010: row[31]?.toString() || "",
                Ad011: row[32]?.toString() || "",
                Ad012: row[33]?.toString() || "",
                Ad013: row[34]?.toString() || "",
                Ad014: row[35]?.toString() || "",
                Ad015: row[36]?.toString() || "",
                Ad016: row[37]?.toString() || "",
                XY017: row[38]?.toString() || "",
                Ji023: row[39]?.toString() || "",
                Ji024: row[40]?.toString() || "",
                XY018: row[41]?.toString() || "",
                XY019: row[42]?.toString() || "",
                Ji025: row[43]?.toString() || "",
                Ji026: row[44]?.toString() || "",
                Ji001: row[45]?.toString() || "",
                Ji002: row[46]?.toString() || "",
                Ji022: row[47]?.toString() || "",
                XY020: row[48]?.toString() || "",
                XY021: row[49]?.toString() || "",
                XY022: row[50]?.toString() || "",
                Ji003: row[51]?.toString() || "",
                Ji004: row[52]?.toString() || "",
                Ji005: row[53]?.toString() || "",
                Ji006: row[54]?.toString() || "",
                Ji007: row[55]?.toString() || "",
                Ji008: row[56]?.toString() || "",
                Ji009: row[57]?.toString() || "",
                Ji010: row[58]?.toString() || "",
                Ji011: row[59]?.toString() || "",
                Ji012: row[60]?.toString() || "",
                Ji013: row[61]?.toString() || "",
                Ji014: row[62]?.toString() || "",
                Ji015: row[63]?.toString() || "",
                Ji016: row[64]?.toString() || "",
                Ji017: row[65]?.toString() || "",
                Ji018: row[66]?.toString() || "",
                Ji019: row[67]?.toString() || "",
                Ji020: row[68]?.toString() || "",
                Ji021: row[69]?.toString() || "",
                Py001: row[70]?.toString() || "",
                Py002: row[71]?.toString() || "",
                Py003: row[72]?.toString() || "",
                Py004: row[73]?.toString() || "",
                Py005: row[74]?.toString() || "",
                Py006: row[75]?.toString() || "",
                Py007: row[76]?.toString() || "",
                Py009: row[77]?.toString() || "",
                Py010: row[78]?.toString() || "",
                Py011: row[79]?.toString() || ""
            };
        }
    };
});
